import {StyledHomeHeaderContainer} from '../styles/styles'
const HomePageHeader = () => (
    <StyledHomeHeaderContainer>
        <h1>Jobs</h1>
        <p>
            Hello and welcome! :) This app was generated by the Create React App
            template and bootstrapped with Redux, React Router, TypeScript, ESlint,
            Prettier for you. Take a look around ;)
        </p>

    </StyledHomeHeaderContainer>
)
export default HomePageHeader